# version: "3.9"

services:
  ####################################################################################################
  # Web
  ####################################################################################################
  web:
    container_name: bits-n-bytes-web
    image: bits-n-bytes-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./web/.env.local
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # PHP
  ####################################################################################################
  php:
    container_name: bits-n-bytes-php
    # Build PHP image from .docker/php directory
    build: .docker/php
    # Map port 5173 on host to port 5173 in container
    ports:
      - 5173:5173
    # Mount current directory as volume in /var/www in container with caching
    volumes:
      - ./service:/var/www:cached
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # Nginx
  ####################################################################################################
  nginx:
    container_name: bits-n-bytes-nginx
    image: nginx
    # Map port 80 on host to port 80 in container
    ports:
      - 80:80
    # Mount current directory as volume in /var/www in container
    # Mount Nginx configuration files from .docker/nginx directory
    volumes:
      - ./service:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    # Depend on PHP service
    depends_on:
      - php
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # PostgreSQL
  ####################################################################################################
  db:
    container_name: bits-n-bytes-db
    # Use PostgreSQL 16 image from Docker Hub
    image: postgres:16
    # Map port 5432 on host to port 5432 in container
    ports:
      - 5432:5432
    # Mount data directory and SQL scripts from .docker/db directory
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .docker/db/sql:/docker-entrypoint-initdb.d
    # Set environment variables for PostgreSQL
    environment:
      - POSTGRES_DB=bits_n_bytes
      - POSTGRES_USER=bits_n_bytes
      - POSTGRES_PASSWORD=bits_n_bytes
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # pgAdmin
  ####################################################################################################
  pgadmin:
    container_name: bits-n-bytes-pgadmin
    # Use pgAdmin 4 image from Docker Hub
    image: dpage/pgadmin4
    # Map port 5050 on host to port 80 in container
    ports:
      - 5050:80
    # Set environment variables for pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    # Depend on PostgreSQL service
    depends_on:
      - db
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # Adminer
  ####################################################################################################
  adminer:
    container_name: bits-n-bytes-adminer
    # Use Adminer image from Docker Hub
    image: adminer
    # Map port 9090 on host to port 8080 in container
    ports:
      - 9090:8080
    # Depend on PostgreSQL service
    depends_on:
      - db
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # Mailpit
  ####################################################################################################
  mail:
    container_name: bits-n-bytes-mail
    # Use Mailpit image from Docker Hub
    image: axllent/mailpit:latest
    # Map port 8025 on host to port 8025 in container
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - bits-n-bytes-network

  ####################################################################################################
  # Redis
  ####################################################################################################
  redis:
    container_name: bits-n-bytes-redis
    # Use Redis image from Docker Hub
    image: redis:latest
    # Run Redis server with appendonly mode
    command: redis-server --appendonly yes
    # Mount data directory from .docker/redis directory
    volumes:
      - .docker/redis/data:/data
    # Map port 6379 on host to port 6379 in container
    ports:
      - 6379:6379
    networks:
      - bits-n-bytes-network

networks:
  bits-n-bytes-network:
    driver: bridge
    external: true

volumes:
  # Create a named volume for PostgreSQL data
  pgdata: 
    driver: local
