# bits-n-bytes/compose.dev.yaml

version: '3.9'

services:
  web:
    container_name: bits-n-bytes-web-dev
    image: bits-n-bytes-web-dev:0.1.0
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    ports:
      - '5173:3000'
    env_file:
      - ./web/.env.dev
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /usr/src/app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - bits-n-bytes-network

  register:
    build:
      context: ./auth-services/register
      dockerfile: dev.Dockerfile
    container_name: register-service-dev
    image: register-service-dev:0.1.0
    env_file:
      - ./auth-services/register/.env
    volumes:
      - ./auth-services/register:/var/www
      - ./auth-services/register/vendor:/var/www/vendor
    ports:
      - '8001:8000'
    networks:
      - auth-services-network
      - bits-n-bytes-network
    depends_on:
      - postgres

  login:
    build:
      context: ./auth-services/login
      dockerfile: dev.Dockerfile
    container_name: login-service-dev
    image: login-service-dev:0.1.0
    env_file:
      - ./auth-services/login/.env
    volumes:
      - ./auth-services/login:/var/www
      - ./auth-services/login/vendor:/var/www/vendor
    ports:
      - '8002:8000'
    networks:
      - auth-services-network
      - bits-n-bytes-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16.3-alpine3.18
    container_name: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./auth-services/.env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auth-services-network

networks:
  bits-n-bytes-network:
    driver: bridge
  auth-services-network:
    driver: bridge
